base_images:
  manila-csi-driver-operator-test:
    name: "4.19"
    namespace: ocp
    tag: manila-csi-driver-operator-test
  openstack-cinder-csi-driver-operator-test:
    name: "4.19"
    namespace: ocp
    tag: openstack-cinder-csi-driver-operator-test
  openstack-installer:
    name: "4.19"
    namespace: ocp
    tag: openstack-installer
  openstack-tests:
    name: "4.19"
    namespace: ocp
    tag: openstack-tests
  stolostron:
    name: builder
    namespace: stolostron
    tag: go1.21-linux
  upi-installer:
    name: "4.19"
    namespace: ocp
    tag: upi-installer
  vsphere-ci-python:
    name: vsphere-python
    namespace: ci
    tag: latest
releases:
  initial:
    candidate:
      product: ocp
      relative: 1
      stream: ci
      version: "4.19"
  latest:
    candidate:
      product: ocp
      stream: ci
      version: "4.19"
resources:
  '*':
    requests:
      cpu: 100m
      memory: 200Mi
tests:
- as: e2e-aws-ovn-techpreview
  interval: 168h
  steps:
    cluster_profile: aws-2
    env:
      FEATURE_SET: TechPreviewNoUpgrade
    observers:
      enable:
      - observers-resource-watch
    workflow: openshift-e2e-aws-ovn
- as: e2e-aws-ovn-no-capabilities
  interval: 168h
  steps:
    cluster_profile: aws
    env:
      ADDITIONAL_ENABLED_CAPABILITIES: MachineAPI CloudCredential CloudControllerManager
        Ingress
      BASELINE_CAPABILITY_SET: None
      PERSISTENT_MONITORING: "false"
      TEST_SKIPS: check registry.redhat.io is available and samples operator can import
        sample imagestreams
    observers:
      enable:
      - observers-resource-watch
    workflow: openshift-e2e-aws-ovn
- as: e2e-aws-ovn
  interval: 168h
  steps:
    cluster_profile: aws-3
    observers:
      enable:
      - observers-resource-watch
    workflow: openshift-e2e-aws-ovn
- as: e2e-aws-ovn-proxy
  interval: 168h
  steps:
    cluster_profile: aws
    observers:
      enable:
      - observers-resource-watch
    workflow: openshift-e2e-aws-proxy
- as: e2e-aws-ovn-serial
  interval: 168h
  steps:
    cluster_profile: aws-3
    observers:
      enable:
      - observers-resource-watch
    workflow: openshift-e2e-aws-ovn-serial
- as: e2e-aws-ovn-tls-13
  interval: 168h
  steps:
    cluster_profile: aws
    env:
      TEST_SUITE: openshift/conformance/parallel
    observers:
      enable:
      - observers-resource-watch
    workflow: openshift-e2e-aws-ovn-tls-13
- as: e2e-aws-ovn-techpreview-serial
  interval: 168h
  steps:
    cluster_profile: aws
    env:
      FEATURE_SET: TechPreviewNoUpgrade
    observers:
      enable:
      - observers-resource-watch
    workflow: openshift-e2e-aws-ovn-serial
  timeout: 5h0m0s
- as: e2e-aws-ovn-upgrade
  interval: 168h
  steps:
    cluster_profile: aws
    env:
      FAIL_ON_CORE_DUMP: "true"
      TEST_TYPE: upgrade-conformance
    observers:
      enable:
      - observers-resource-watch
    workflow: openshift-upgrade-aws-ovn
- as: e2e-aws-ovn-upgrade-out-of-change
  interval: 168h
  steps:
    cluster_profile: aws
    dependencies:
      OPENSHIFT_INSTALL_RELEASE_IMAGE_OVERRIDE: release:latest
      OPENSHIFT_UPGRADE_RELEASE_IMAGE_OVERRIDE: release:initial
    env:
      FAIL_ON_CORE_DUMP: "true"
      TEST_TYPE: upgrade-conformance
    observers:
      enable:
      - observers-resource-watch
    workflow: openshift-upgrade-aws-ovn
- as: e2e-aws-cilium
  interval: 168h
  steps:
    cluster_profile: aws
    observers:
      enable:
      - observers-resource-watch
    workflow: openshift-e2e-aws-cilium
- as: e2e-azure-ovn-techpreview
  interval: 168h
  steps:
    cluster_profile: azure-2
    env:
      BASE_DOMAIN: ci2.azure.devcluster.openshift.com
      FEATURE_SET: TechPreviewNoUpgrade
    observers:
      enable:
      - observers-resource-watch
    workflow: openshift-e2e-azure-ovn
- as: e2e-azure-ovn-serial
  interval: 168h
  steps:
    cluster_profile: azure-2
    env:
      BASE_DOMAIN: ci2.azure.devcluster.openshift.com
    observers:
      enable:
      - observers-resource-watch
    workflow: openshift-e2e-azure-serial
- as: e2e-azure-ovn-techpreview-serial
  interval: 168h
  steps:
    cluster_profile: azure-2
    env:
      BASE_DOMAIN: ci2.azure.devcluster.openshift.com
      FEATURE_SET: TechPreviewNoUpgrade
    observers:
      enable:
      - observers-resource-watch
    workflow: openshift-e2e-azure-serial
  timeout: 5h0m0s
- as: e2e-azure-ovn-upgrade
  interval: 168h
  steps:
    cluster_profile: azure-2
    env:
      BASE_DOMAIN: ci2.azure.devcluster.openshift.com
      FAIL_ON_CORE_DUMP: "true"
      TEST_TYPE: upgrade-conformance
    observers:
      enable:
      - observers-resource-watch
    workflow: openshift-upgrade-azure-ovn
  timeout: 5h30m0s
- as: e2e-azure-ovn-upgrade-out-of-change
  interval: 168h
  steps:
    cluster_profile: azure-2
    dependencies:
      OPENSHIFT_INSTALL_RELEASE_IMAGE_OVERRIDE: release:latest
      OPENSHIFT_UPGRADE_RELEASE_IMAGE_OVERRIDE: release:initial
    env:
      BASE_DOMAIN: ci2.azure.devcluster.openshift.com
      FAIL_ON_CORE_DUMP: "true"
      TEST_TYPE: upgrade-conformance
    observers:
      enable:
      - observers-resource-watch
    workflow: openshift-upgrade-azure-ovn
  timeout: 5h30m0s
- as: e2e-azure-cilium
  interval: 168h
  steps:
    cluster_profile: azure-2
    env:
      BASE_DOMAIN: ci2.azure.devcluster.openshift.com
    observers:
      enable:
      - observers-resource-watch
    workflow: openshift-e2e-azure-cilium
- as: e2e-azure-ovn
  interval: 168h
  steps:
    cluster_profile: azure-2
    env:
      BASE_DOMAIN: ci2.azure.devcluster.openshift.com
      FAIL_ON_CORE_DUMP: "true"
    observers:
      enable:
      - observers-resource-watch
    workflow: openshift-e2e-azure-ovn
- as: e2e-gcp-ovn-techpreview
  interval: 168h
  steps:
    cluster_profile: gcp-3
    env:
      FEATURE_SET: TechPreviewNoUpgrade
    observers:
      enable:
      - observers-resource-watch
    workflow: openshift-e2e-gcp-ovn
- as: e2e-gcp-ovn
  interval: 168h
  steps:
    cluster_profile: gcp-openshift-gce-devel-ci-2
    env:
      FAIL_ON_CORE_DUMP: "true"
    observers:
      enable:
      - observers-resource-watch
    workflow: openshift-e2e-gcp-ovn
- as: e2e-gcp-ovn-xpn
  interval: 168h
  steps:
    cluster_profile: gcp
    observers:
      enable:
      - observers-resource-watch
    workflow: openshift-e2e-gcp-xpn
- as: e2e-gcp-ovn-mount-ns-hiding
  interval: 168h
  steps:
    cluster_profile: gcp-3
    env:
      FAIL_ON_CORE_DUMP: "true"
      MOUNT_NS_HIDING_ENABLED: "true"
      MOUNT_NS_HIDING_LOG: "2"
    observers:
      enable:
      - observers-resource-watch
    workflow: openshift-e2e-gcp-mount-ns-hiding
- as: e2e-gcp-ovn-techpreview-serial
  interval: 168h
  steps:
    cluster_profile: gcp-3
    env:
      FEATURE_SET: TechPreviewNoUpgrade
    observers:
      enable:
      - observers-resource-watch
    workflow: openshift-e2e-gcp-serial
  timeout: 5h0m0s
- as: e2e-gcp-ovn-upgrade
  cluster: build02
  interval: 168h
  steps:
    cluster_profile: gcp-3
    env:
      TEST_TYPE: upgrade-conformance
    observers:
      enable:
      - observers-resource-watch
    workflow: openshift-upgrade-gcp-ovn
- as: e2e-gcp-ovn-upgrade-out-of-change
  cluster: build02
  interval: 168h
  steps:
    cluster_profile: gcp-3
    dependencies:
      OPENSHIFT_INSTALL_RELEASE_IMAGE_OVERRIDE: release:latest
      OPENSHIFT_UPGRADE_RELEASE_IMAGE_OVERRIDE: release:initial
    env:
      TEST_TYPE: upgrade-conformance
    observers:
      enable:
      - observers-resource-watch
    workflow: openshift-upgrade-gcp-ovn
- as: e2e-gcp-cilium
  interval: 168h
  steps:
    cluster_profile: gcp-3
    observers:
      enable:
      - observers-resource-watch
    workflow: openshift-e2e-gcp-cilium
- as: e2e-gcp-secureboot
  interval: 168h
  steps:
    cluster_profile: gcp-openshift-gce-devel-ci-2
    observers:
      enable:
      - observers-resource-watch
    workflow: openshift-e2e-gcp-secureboot
  timeout: 6h0m0s
- as: e2e-aws-upgrade-ovn-single-node
  interval: 168h
  steps:
    cluster_profile: aws
    env:
      TEST_TYPE: upgrade-conformance
    observers:
      enable:
      - observers-resource-watch
    workflow: openshift-upgrade-aws-single-node
- as: e2e-aws-upgrade-ovn-single-node-4vcpu-compute
  interval: 168h
  steps:
    cluster_profile: aws-3
    env:
      SINGLE_NODE_AWS_INSTANCE_TYPE: r6i.xlarge
      TEST_SUITE: upgrade-conformance
    workflow: openshift-upgrade-aws-single-node
- as: e2e-vsphere-ovn-upgrade
  interval: 168h
  steps:
    cluster_profile: vsphere-elastic
    observers:
      enable:
      - observers-resource-watch
    workflow: openshift-upgrade-vsphere
- as: e2e-azure-runc-upgrade
  cron: '@daily'
  steps:
    cluster_profile: azure-2
    env:
      BASE_DOMAIN: ci2.azure.devcluster.openshift.com
      FAIL_ON_CORE_DUMP: "true"
      TEST_TYPE: upgrade-conformance
    observers:
      enable:
      - observers-resource-watch
    workflow: openshift-upgrade-azure-runc
- as: e2e-gcp-runc-upgrade
  cluster: build02
  cron: '@daily'
  steps:
    cluster_profile: gcp-openshift-gce-devel-ci-2
    env:
      FAIL_ON_CORE_DUMP: "true"
      TEST_TYPE: upgrade-conformance
    observers:
      enable:
      - observers-resource-watch
    workflow: openshift-upgrade-gcp-runc
- as: e2e-aws-runc-upgrade
  cron: '@daily'
  steps:
    cluster_profile: aws
    env:
      FAIL_ON_CORE_DUMP: "true"
      TEST_TYPE: upgrade-conformance
    observers:
      enable:
      - observers-resource-watch
    workflow: openshift-upgrade-aws-runc
- as: e2e-vsphere-runc-upgrade
  cron: '@daily'
  steps:
    cluster_profile: vsphere-elastic
    observers:
      enable:
      - observers-resource-watch
    workflow: openshift-upgrade-vsphere-runc
- as: e2e-openstack-fips
  minimum_interval: 56h
  steps:
    cluster_profile: openstack-vexxhost
    env:
      FIPS_ENABLED: "true"
      TEST_SUITE: experimental/reliability/minimal
    pre:
    - chain: ipi-openstack-pre
    - ref: fips-check
    workflow: openshift-e2e-openstack-ipi
- as: e2e-openstack-proxy
  minimum_interval: 144h
  steps:
    cluster_profile: openstack-vh-mecha-central
    workflow: openshift-e2e-openstack-proxy
- as: e2e-openstack-externallb
  minimum_interval: 168h
  steps:
    cluster_profile: openstack-vh-mecha-central
    workflow: openshift-e2e-openstack-external-lb
- as: e2e-openstack-nfv-intel
  minimum_interval: 144h
  steps:
    cluster_profile: openstack-nfv
    workflow: openshift-e2e-openstack-nfv
- as: e2e-openstack-nfv-mellanox
  minimum_interval: 144h
  steps:
    cluster_profile: openstack-nfv
    env:
      ADDITIONAL_WORKERS_NETWORKS: mellanox-dpdk
      OPENSTACK_DPDK_NETWORK: mellanox-dpdk
      OPENSTACK_SRIOV_NETWORK: mellanox-sriov
    workflow: openshift-e2e-openstack-nfv
- as: e2e-openstack-additional-ipv6-network
  minimum_interval: 144h
  steps:
    cluster_profile: openstack-hwoffload
    workflow: openshift-e2e-openstack-ipv6
- as: e2e-openstack-csi-manila
  minimum_interval: 144h
  steps:
    cluster_profile: openstack-vh-mecha-central
    workflow: openshift-e2e-openstack-csi-manila
- as: e2e-openstack-csi-cinder
  minimum_interval: 144h
  steps:
    cluster_profile: openstack-vh-mecha-central
    env:
      TEST_SKIPS: should concurrently access the volume and restored snapshot from
        pods on the same node
    workflow: openshift-e2e-openstack-csi-cinder
- as: e2e-openstack-ovn-parallel
  minimum_interval: 48h
  steps:
    cluster_profile: openstack-vexxhost
    env:
      ROTATE_CLOUD_CREDENTIALS: "true"
      TEST_SUITE: openshift/conformance/parallel
    workflow: openshift-e2e-openstack-ipi
- as: e2e-openstack-ovn-serial
  minimum_interval: 48h
  steps:
    cluster_profile: openstack-vexxhost
    env:
      ROTATE_CLOUD_CREDENTIALS: "true"
      TEST_SUITE: openshift/conformance/serial
    workflow: openshift-e2e-openstack-ipi
  timeout: 5h0m0s
- as: e2e-openstack-dualstack-upi
  minimum_interval: 240h
  steps:
    cluster_profile: openstack-hwoffload
    env:
      CONFIG_TYPE: dual-stack-upi
      OPENSTACK_COMPUTE_FLAVOR: m1.xlarge
      OPENSTACK_TEST_SKIPS: The OpenStack platform creates Worker nodes in a server
        group\|The OpenStack platform creates Control plane nodes in a server group
      TEST_SKIPS: Services Secondary IP Family \[LinuxOnly\] should function for service
        endpoints using hostNetwork
      TEST_SUITE: experimental/reliability/minimal
    workflow: openshift-e2e-openstack-upi
- as: e2e-openstack-ovn-password
  minimum_interval: 48h
  steps:
    cluster_profile: openstack-vexxhost
    env:
      OPENSTACK_AUTHENTICATION_METHOD: password
    workflow: openshift-e2e-openstack-ipi
- as: e2e-openstack-ovn-etcd-scaling
  minimum_interval: 168h
  steps:
    cluster_profile: openstack-vexxhost
    observers:
      enable:
      - observers-resource-watch
    workflow: openshift-e2e-openstack-etcd-scaling
- as: e2e-openstack-dualstack
  minimum_interval: 96h
  steps:
    cluster_profile: openstack-hwoffload
    workflow: openshift-e2e-openstack-dualstack
- as: e2e-openstack-dualstack-v6primary
  minimum_interval: 96h
  steps:
    cluster_profile: openstack-hwoffload
    env:
      CONFIG_TYPE: dualstack-v6primary
    workflow: openshift-e2e-openstack-dualstack
- as: e2e-openstack-singlestackv6
  minimum_interval: 96h
  steps:
    cluster_profile: openstack-hwoffload
    env:
      CONFIG_TYPE: singlestackv6
    workflow: openshift-e2e-openstack-singlestackv6
- as: e2e-openstack-ccpmso
  minimum_interval: 240h
  steps:
    cluster_profile: openstack-vexxhost
    env:
      TEST_SUITE: experimental/reliability/minimal
    test:
    - as: openstack-test-cpms
      commands: |
        dir=$GOPATH/src/github.com/openshift/cluster-control-plane-machine-set-operator
        git clone https://github.com/openshift/cluster-control-plane-machine-set-operator --branch release-4.19 --depth=1 $dir
        export OPENSTACK_CONTROLPLANE_FLAVOR_ALTERNATE="$(<"${SHARED_DIR}/OPENSTACK_CONTROLPLANE_FLAVOR_ALTERNATE")"
        cd $dir
        make e2e-periodic
      from: stolostron
      resources:
        requests:
          cpu: 100m
      timeout: 3h0m0s
    - ref: openshift-e2e-test
    - ref: openstack-test-openstack
    workflow: openshift-e2e-openstack-ipi
  timeout: 7h0m0s
- as: e2e-openstack-ccpmso-zone
  minimum_interval: 240h
  steps:
    cluster_profile: openstack-vh-mecha-az0
    env:
      ETCD_ON_LOCAL_DISK: "true"
      TEST_SUITE: experimental/reliability/minimal
      USE_RAMFS: "false"
    test:
    - as: openstack-test-cpms
      commands: |
        dir=$GOPATH/src/github.com/openshift/cluster-control-plane-machine-set-operator
        git clone https://github.com/openshift/cluster-control-plane-machine-set-operator --branch release-4.19 --depth=1 $dir
        export OPENSTACK_CONTROLPLANE_FLAVOR_ALTERNATE="$(<"${SHARED_DIR}/OPENSTACK_CONTROLPLANE_FLAVOR_ALTERNATE")"
        cd $dir
        test -f "${SHARED_DIR}/proxy-conf.sh" && source "${SHARED_DIR}/proxy-conf.sh"
        make e2e-periodic
      from: stolostron
      resources:
        requests:
          cpu: 100m
      timeout: 3h0m0s
    - ref: openshift-e2e-test
    - ref: openstack-test-openstack
    workflow: openshift-e2e-openstack-ipi
  timeout: 7h0m0s
zz_generated_metadata:
  branch: master
  org: openshift
  repo: release
  variant: ci-4.19
